volumes:
  mysql_data:
  kafka_data:
  zookeeper_data:
  prometheus_data:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  #  zookeeper:
  #    image: bitnami/zookeeper:latest
  #    ports:
  #      - 2181:2181
  #    volumes:
  #      - zookeeper_data:/bitnami/zookeeper
  #    environment:
  #      ALLOW_ANONYMOUS_LOGIN: yes
  #
  #  kafka:
  #    image: bitnami/kafka:latest
  #    ports:
  #      - 9092:9092
  #      - 9094:9094
  #    environment:
  #      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@<your_host>:9093
  #      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  #      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
  #      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #    volumes:
  #      - kafka_data:/bitnami/kafka
  #    depends_on:
  #      - zookeeper

  azure-cli:
    image: mcr.microsoft.com/azure-cli
    tty: true

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus